# Generated by Django 3.0 on 2021-05-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('step_number', models.IntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Tutorial')),
            ],
        ),
    ]
