# Generated by Django 3.0 on 2021-05-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialstep',
            options={'ordering': ('-tutorial__id', 'step_number')},
        ),
    ]
