# Generated by Django 3.2.3 on 2021-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='client_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
