# Generated by Django 3.0 on 2021-05-22 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('resolved', models.BooleanField(default=True)),
                ('device', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
