# Generated by Django 3.0 on 2021-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='client_id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
